[package]
name = "shorturl"
version = "0.1.0"
authors = ["Owen Chia <aptx945@gmail.com>"]

[dependencies]
actix = "0.5"
actix-web = "0.5"
redis = "0.8.0"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
rand = "*"
